# Generated by Django 3.1.5 on 2021-02-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='mix',
            name='multitrack',
        ),
        migrations.RemoveField(
            model_name='mix',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Mix',
        ),
    ]
