# Generated by Django 3.1.5 on 2021-01-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
    ]
