# Generated by Django 3.1.5 on 2021-01-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitracks', '0002_remove_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitrack',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='multitracks.genre'),
        ),
    ]
