# Generated by Django 3.1.5 on 2021-01-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitracks', '0003_auto_20210122_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='contact',
            field=models.URLField(null=True),
        ),
    ]
