# Generated by Django 3.1.5 on 2021-01-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitracks', '0004_auto_20210122_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='contact',
            field=models.URLField(blank=True, null=True),
        ),
    ]
