# Generated by Django 3.1.5 on 2021-01-26 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multitracks', '0005_auto_20210122_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitrack',
            name='file_size',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
