# Generated by Django 3.1.5 on 2021-02-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitracks', '0006_multitrack_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitrack',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multitrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitracks.multitrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('multitrack', 'user')},
            },
        ),
        migrations.AddField(
            model_name='multitrack',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_ads', through='multitracks.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
