# Generated by Django 3.1.2 on 2021-02-01 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitracks', '0007_auto_20210201_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitrack',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_multitracks', through='multitracks.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
