# Generated by Django 3.1.5 on 2021-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
